# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Split' do
    pod 'Venmo-iOS-SDK', '~>1.3'
    pod 'Parse'
    pod 'Facebook-iOS-SDK'
end

target 'SplitTests' do

end

